---
deployment:
  tasks:
    - export NODE_ENV=production
    - npm install
    - npm run build
    - /bin/rm -rf $DEPLOYMENT_DIR/*       # delete all old files
    - /bin/cp -r dist/* $DEPLOYMENT_DIR   # copy build only
    - /bin/cp .htaccess $DEPLOYMENT_DIR || true